name: Deploy to Vercel
on:
  push:
    branches:
      - pre-firebase
  pull_request_target:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npx vercel@25.1.0 pull --yes --token=${VERCEL_TOKEN}
        working-directory: ./
        env:
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - run: |
          npx vercel@25.1.0 build
        if: github.event_name == 'pull_request_target'
        working-directory: ./
        env:
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      - uses: amondnet/vercel-action@v25
        id: now-deployment-staging
        if: github.event_name == 'pull_request_target'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: --prebuilt
          working-directory: ./
          # alias-domains: |
          #   staging.nextjs.vercel-action.amond.dev
          #   pr-{{PR_NUMBER}}.nextjs.vercel-action.amond.dev
      - name: production or not
        id: prod_or_not
        run: |
          if [ "$REF" == 'refs/heads/pre-firebase' ]
          then
              echo "vercel-args=--prod --prebuilt" >> $GITHUB_OUTPUT
          else
              echo "vercel-args=--prebuilt" >> $GITHUB_OUTPUT
          fi
        env:
          REF: ${{ github.ref }}
      - run: |
          npx vercel@25.1.0 build --prod
        if: github.event_name == 'push'
        working-directory: ./
        env:
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      - uses: amondnet/vercel-action@v25
        id: now-deployment-production
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: ${{ steps.prod_or_not.outputs.vercel-args }}
          working-directory: ./
          # alias-domains: |
          #   {{BRANCH}}.nextjs.vercel-action.amond.dev
